### ISSUE TITLE
Maybe I am writing wrong how to integrate the pictures to the text because I can't see them.

### ISSUE THREAD

**Issue by Shayros** [marskar/biof309_fall2018#10]
#1. Downloading the datasets

Once you arrived at the site, you are going to search for the things that you would like to study. For instance, you can write in the search breast cancer and all the data available that used breast cancer will show up.

**As an example I will be using three datasets of RNA-seq expression of lung epithelial and mesenchymal cells at different embryonic stage:**

*GSM2319567 (lung 9.5 embryo expression)

*GSM3027039 (lung 10.5 embryo expression)

*GSM3027047 (lung 11.5 embryo expression)

To download the data you can go to end and dowload the series matrix. GSE files are the one that contain the data to be analyzed and GPL files contain the annotation. When working with your own questions I recommend downloading both to help you know what mRNA data you are analyzing.

I am going to include the steps to download one of the datasets and save this data to help you find the data when the files are added as a supplement information instead of a series matrix.

-Look on this data on the search bar

-In the bottom of the pages sometimes are instruction that will help you find the data. As you see in the instruction "Raw data are available in SRA"

![Finding the data step one](https://github.com/Shayros/Developing-hypotheses/blob/master/figures/Finding%20the%20data%20step%20one.png)

-Now, find your dataset!

![Finding the data step two](https://github.com/Shayros/Developing-hypotheses/blob/master/figures/Finding%20the%20data%20step%20two.png)

-Downloading the datasets

![Finding the data step three](https://github.com/Shayros/Developing-hypotheses/blob/master/figures/Finding%20the%20data%20step%20three.png)

-Final step

![Finding the data last step](https://github.com/Shayros/Developing-hypotheses/blob/master/figures/Finding%20the%20data%20last%20step.png)

**You have your data. Now what?**

-You need to filter the data either in Excel or python to facilitates its use.

**Comment by marskar** [comment]
I submitted a pull request that should fix the problem with the images. 
https://github.com/Shayros/Developing-hypotheses/pull/1
I'll close the issue now, but if you need anything else, just let me know!
