### ISSUE TITLE
Uploading my project files to GitHub repo

### ISSUE THREAD

**Issue by jschrope40** [marskar/biof309_fall2018#12]
I am trying to upload my files to a new GitHub repo (or an old one, I don't really care). All of my online searching through JetBrains documentation says to click on the "Local Changes" tab, then commit and push" but I do not have that "Local Changes" tab available to me.

I expect that the "Local Changes" tab is only present if you initially opened the project from a pre-made GitHub repo with intent to edit the files then push them back. I, however, started the project on my computer, and now want to upload all my files to a repo on GitHub. Do you have any quick advice? I know we did this in an early class I could probably just go back and watch that again. 

I am able to "commit" the files by pressing a green check mark at the top right of my PyCharm screen, but do not know how to push them. 

I have tried this tutorial "https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/" in the terminal in PyCharm with little avail. Any suggestions.

**Comment by marskar** [comment]
Can you bring up the action list and type in push?
The keyboard shortcut to push is Ctrl/Cmd+Shift+K.
