### ISSUE TITLE
Converting Jupyter Markdown into slides

### ISSUE THREAD

**Issue by cchungo1** [marskar/biof309_fall2018#14]
For some reason we are having trouble converting our markdown file in Juypter to slides. 

I did View → Cell Toolbar → Slideshow

Then I selected the ones to be slides and then I typed into my terminal: 

jupyter nbconvert Jupyter\ Slides.ipynb --to slides --post serve

However I then received this message: 
![capture](https://user-images.githubusercontent.com/43455544/49843948-fd339680-fd8e-11e8-8455-fc0fd6699a97.PNG)

I cannot seem to convert the slides.

**Comment by marskar** [comment]
Please try the instruction at the bottom of this page: https://marskar.github.io/slides/
