### ISSUE TITLE
Appending Jupyter Notebook link for Binder

### ISSUE THREAD

**Issue by ContoakleyK** [marskar/biof309_fall2018#19]
I tried to add the binder button and link to open my notebook from the markdown file on my repo, but I have not been able to solve the error.

Thank you, Kevin

https://github.com/BIOF309/group-project-rmndr

**Comment by marskar** [comment]
I fixed the link: https://mybinder.org/v2/gh/BIOF309/group-project-rmndr/master?urlpath=lab/notebooks/PACT%20data%20-%20Final.ipynb
